---
# Ansible playbook with ROLES
# Home work #9

- name: builder-server configuration
  hosts: builder
  become: yes
  roles:
  - common
  - builder
  - security


- name: web-server configuration
  hosts: web
  become: yes
  roles:
  - common
  - webserver
  - webserverindocker
  - security
